name: Sample Workflow
on: [push]
jobs:
  First-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
    
      - name: Execute Gradle build
        run: ./gradlew build
      - name: listing folder
        run: |
            ls -a
            cd build/libs
            ls -a
      - uses: jfrog/setup-jfrog-cli@v2
        env:
        # JFrog platform url (for example: https://acme.jfrog.io) 
          JF_URL: ${{ secrets.JF_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
      - run: |
          jf rt ping 
          jf rt u "build/libs/*" example-repo-local/artifacts/