on: [push]
name: Integrate Gradle project with Sonarqube and Github Actions
jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: |
            chmod +x gradlew
            ./gradlew build
    - name: sonar scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      with:
        args: >
          -Dsonar.organization=pallavipendyala
          -Dsonar.projectKey=pallavipendyala_gradlepro
          -Dsonar.java.binaries=build/classes/
    - name: SonarQube Quality Gate check
      id: sonarqube-quality-gate-check
      uses: sonarsource/sonarqube-quality-gate-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

    - name: Download Fortify ScanCentral Client
      uses: fortify/gha-setup-scancentral-client@v1
    - name: Package Code + Dependencies
      run: scancentral package $PACKAGE_OPTS -o package.zip
      env:
        PACKAGE_OPTS: "-bt gradle"
      
      # Start Fortify on Demand SAST scan. Be sure to set secrets/variables for your desired configuration.
    - name: Download Fortify on Demand Universal CI Tool
      uses: fortify/gha-setup-fod-uploader@v1
    - name: Perform SAST Scan
      run: java -jar $FOD_UPLOAD_JAR -z package.zip -aurl $FOD_API_URL -purl $FOD_URL -rid "$FOD_RELEASE_ID" -tc "$FOD_TENANT" -uc "$FOD_USER" "$FOD_PAT" $FOD_UPLOADER_OPTS -n "$FOD_UPLOADER_NOTES"
      env: 
        FOD_UPLOAD_JAR: "build/libs/(*.jar)"
        FOD_TENANT: ${{ secrets.FOD_TENANT }}  
        FOD_USER: ${{ secrets.FOD_USER }}
        FOD_PAT: ${{ secrets.FOD_PAT }}
        FOD_RELEASE_ID: ${{ secrets.FOD_RELEASE_ID }}
        FOD_URL: "https://ams.fortify.com/"
        FOD_API_URL: "https://api.ams.fortify.com/"
        FOD_UPLOADER_OPTS: "-ep 2 -pp 0"
        FOD_UPLOADER_NOTES: 'Triggered by GitHub Actions (${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})'
    - uses: jfrog/setup-jfrog-cli@v2
      env:
        # JFrog platform url (for example: https://acme.jfrog.io) 
        JF_URL: ${{ secrets.JF_URL }}
        JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
      
    - run: |
          jf rt ping 
          jf rt u "build/libs/(*.jar)" example-repo-local/{1} --sync-deletes="example-repo-local/"


